name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: Checkout
      uses: actions/checkout@master
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Upload
      run: node scripts/upload.js --SecretId $SecretId --SecretKey $SecretKey
      env:
        SecretId: ${{ secrets.SecretId }}
        SecretKey: ${{ secrets.SecretKey }}
